version: '3.8'

services:
  acoes:
    build: ./backend/acoes
    ports:
      - "3003:3003"
    volumes:
      - ./backend/acoes:/app
      - ./db/acoes:/app/db 
    environment:
      - FLASK_DEBUG=0

  dolar:
    build: ./backend/dolar
    ports:
      - "3004:3004"
    volumes:
      - ./backend/dolar:/app
      - ./db/dolar:/app/db 
    environment:
      - FLASK_DEBUG=0

  bitcoin:
    build: ./backend/bitcoin
    ports:
      - "3005:3005"
    volumes:
      - ./backend/bitcoin:/app
      - ./db/bitcoin:/app/db 
    environment:
      - FLASK_DEBUG=0

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL_ACOES=http://localhost:3003
      - REACT_APP_API_URL_DOLAR=http://localhost:3004
    depends_on:
      - acoes
      - dolar

volumes:
  db: